# Generated by Django 3.2.3 on 2021-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_v01', '0002_auto_20210524_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_ISSUES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
