# Generated by Django 3.2.3 on 2021-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_v01', '0003_user_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_user',
            name='admin_id',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
