# Generated by Django 3.2.4 on 2021-06-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_v01', '0004_comment_user_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TITLE_BODY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=10000)),
                ('issue_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
